apiVersion: apps/v1
kind: Deployment
metadata:
    name: fastfeet
spec:
    selector:
        matchLabels:
            run: fastfeet
    replicas: 2
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 25%
    template:
        metadata:
            labels:
                run: fastfeet
        spec:
            containers:
            - name: fastfeet
              image: dayvsonsales/fastfeet:latest
              ports:
              - containerPort: 80
